SecuringApps.Application/SecuringApps.Presentation/Controllers/StudentTaskController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SecuringApps.Application.Interfaces;
using SecuringApps.Presentation.Models;
using System;
using System.Linq;
namespace SecuringApps.Presentation.Controllers
{
    public class StudentTaskController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private ILogger<StudentTaskController> _logger;
        private IStudentTaskService _IStudentTaskService;
        private IWebHostEnvironment _env;
        public StudentTaskController
        (
            RoleManager<IdentityRole> roleManager,
            UserManager<ApplicationUser> userManager,
            ILogger<StudentTaskController> logger,
            IStudentTaskService studentTaskService,
            IWebHostEnvironment env
        )
        {
            _IStudentTaskService = studentTaskService;
            _userManager = userManager;
            _roleManager = roleManager;
            _logger = logger;
            _env = env;
        }
        [HttpGet]
        public IActionResult Index()
        {
            _logger.LogInformation("Accessing Tasks");
            var list = _IStudentTaskService.GetStudentTask();

            var getUser = _userManager.Users.Where(x => x.Id == _userManager.GetUserId(User)).ToList();

            var id = getUser.Select(x => x.createdBy);

            var getTasks = from l in list
                           where id.Contains(l.DocumentOwner)
                           select l;

            return View(getTasks);

        }

        [Authorize(Roles = "Teacher")]
        public IActionResult Create()
        {
            _logger.LogInformation("Accessing the Create Task");

            CreateStudentTaskModel model = new CreateStudentTaskModel();
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreateStudentTaskModel createStudentTask)
        {
            try
            {
                _logger.LogInformation("Create Task");

                if (createStudentTask.StudentTask.Deadline <= DateTime.Now)
                {
                    _logger.LogError("Deadline should be greater than today's date");

                    ModelState.AddModelError(string.Empty, "Deadline should be greater than today's date");
                }
                else
                {
                    createStudentTask.StudentTask.DocumentOwner = _userManager.GetUserId(User);
                    if (ModelState.IsValid)
                    {
                        _logger.LogInformation("Creating Task...");

                        _IStudentTaskService.AddStudentTask(createStudentTask.StudentTask);
                    }
                }

            }
            catch (Exception ex)
            {
                var exception = ex.Message;
                ModelState.AddModelError(string.Empty, exception);
                _logger.LogError("Error: " + exception);
                return RedirectToAction("Error", "Home");
            }

            CreateStudentTaskModel model = new CreateStudentTaskModel();
            return View();
        }
    }
}

SecuringApps.Application/SecuringApps.Presentation/Controllers/StudentWorkController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SecuringApps.Application.Interfaces;
using SecuringApps.Presentation.Models;
using SecuringApps.Presentation.Utilities;
using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Cryptography;

namespace SecuringApps.Presentation.Controllers
{
    public class StudentWorkController : Controller
    {
        private IStudentWorkService _studentWorkService;
        private IStudentTaskService _studentTaskService;
        private IWebHostEnvironment _env;
        private readonly RoleManager<IdentityRole> _roleManager;
        private UserManager<ApplicationUser> _userManager;
        private ILogger<StudentWorkController> _logger;

        byte[] pwd = EncyrptFiles.GenerateRandomSalt();

        public StudentWorkController(IStudentWorkService studentWorkService,
                                            IStudentTaskService studentTaskService,
                                            IWebHostEnvironment env,
                                            UserManager<ApplicationUser> userManager,
                                            RoleManager<IdentityRole> roleManager,
                                            ILogger<StudentWorkController> logger)
        {
            _studentWorkService = studentWorkService;
            _studentTaskService = studentTaskService;
            _env = env;
            _userManager = userManager;
            _roleManager = roleManager;
            _logger = logger;
        }

        [Authorize(Roles = "Student")]
        [HttpGet]
        public IActionResult Index(Guid Id)
        {
            _logger.LogInformation("Student accessed its work");
            var _studentWork = _studentWorkService.GetStudentWork();
            var getStudentWork = _studentWork.Where(x => x.workOwner == _userManager.GetUserId(User) || x.workOwner == _userManager.GetUserName(User));
            return View(getStudentWork.ToList());
        }

        [Authorize(Roles = "Teacher")]
        [HttpGet]
        public IActionResult AllStudentWork()
        {
            _logger.LogInformation("Teacher accessed its work");

            var allStudent = _studentWorkService.GetStudentWork();
            return View(allStudent);
        }

        [Authorize(Roles = "Student")]
        [HttpGet]
        public IActionResult Create(string Id)
        {
            _logger.LogInformation("Student is creating work");
            Id = Id.Replace("|", "/").Replace("_", "+").Replace("$", "=");
            string output = Encryption.SymmetricDecrypt(Id);

            Guid taskId = new Guid(output);

            var taskList = _studentTaskService.GetStudentTask();
            var value = taskList.Where(x => x.Id == taskId);

            CreateStudentWorkModel model = new CreateStudentWorkModel();
            model.StudentTasks = value.ToList();

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Student")]
        public IActionResult Create(CreateStudentWorkModel data, IFormFile file)
        {
            CreateStudentWorkModel model = new CreateStudentWorkModel();
            model.StudentTasks = _studentTaskService.GetStudentTask().ToList();
            var value = model.StudentTasks.Where(x => x.Id == data.StudentWork.StudentTask.Id);

            try
            {
                _logger.LogInformation("Creating work..");
                if (file != null)
                {
                    if (Path.GetExtension(file.FileName) == ".pdf" || Path.GetExtension(file.FileName) == ".PDF")
                    {
                        _logger.LogInformation("Checking file extension");
                        data.StudentWork.submittedOn = DateTime.Now;

                        var StudentTask = _studentTaskService.GetStudentTask().ToList();
                        var val = from a in StudentTask
                                  where a.Id.Equals(data.StudentWork.StudentTask.Id)
                                  select a;

                        var StudentWork = _studentWorkService.GetStudentWork().ToList();
                        var vals = from v in StudentWork
                                   where v.StudentTask.Id.Equals(data.StudentWork.StudentTask.Id) && v.workOwner.Equals(_userManager.GetUserName(User))
                                   select v;
                        foreach (var item in val)
                        {
                            _logger.LogInformation("Task exists, starting validation");
                            if (DateTime.Now > item.Deadline)
                            {
                                _logger.LogInformation("Submission date expired");
                                ModelState.AddModelError(string.Empty, "Submission date expired.");
                                break;
                            }
                            if (vals.Any())
                            {
                                _logger.LogInformation("Work Submitted");
                                ModelState.AddModelError(string.Empty, "Your work is already submitted");
                                break;
                            }
                            else
                            {
                                if (file.Length > 0)
                                {
                                    _logger.LogInformation("Work Submitted");
                                    string newFilename = Guid.NewGuid() + Path.GetExtension(file.FileName);

                                    string absolutePath = _env.ContentRootPath + @"\Files\";

                                    var stream = System.IO.File.Create(absolutePath + file.FileName);

                                    file.CopyTo(stream);

                                    _logger.LogInformation("File copied");
                                    stream.Close();

                                    var keys = EncyrptFiles.GenerateAsymmetricKey();
                                    using (var s = System.IO.File.Open(absolutePath + file.FileName, FileMode.Open))
                                    {
                                        data.StudentWork.filePath = @"\Files\" + file.FileName;

                                        MemoryStream FileM = new MemoryStream();

                                        file.CopyTo(FileM);

                                        s.CopyTo(FileM);

                                        s.Close();
                                        var fileName = EncyrptFiles.FileEncrypt(absolutePath + file.FileName, pwd);


                                        if (CompareFileHashes(fileName))
                                        {
                                            break;
                                        }
                                        else
                                        {
                                            var signature = Convert.ToBase64String(EncyrptFiles.DigitalSign(keys.PrivateKey, FileM));

                                            data.StudentWork.isDigitallySigned = EncyrptFiles.VerifySignature(keys.PublicKey, FileM, Convert.FromBase64String(signature));
                                            data.StudentWork.filePath = fileName;
                                            data.StudentWork.signature = signature;

                                            System.IO.File.Delete(absolutePath + file.FileName);
                                        }
                                    }

                                    data.StudentWork.workOwner = _userManager.GetUserName(User);

                                    _studentWorkService.AddStudentWork(data.StudentWork);
                                    break;
                                }
                            }
                        }
                    }
                    else
                    {
                        _logger.LogError("File Extension allowed is PDF");
                        ModelState.AddModelError(string.Empty, "File Extension allowed is PDF");
                    }

                }
                else
                {
                    _logger.LogError("Document not attacghed.");
                    ModelState.AddModelError(string.Empty, "Please attach document");
                }
            }
            catch (Exception ex)
            {

                var error = ex.Message;

                _logger.LogError("Error: " + error);
                error = ex.InnerException.ToString();

                //log errors
                ViewData["warning"] = "Your work was not added. Check your details";

                //i want to redirect the user to a common page (when there is an error)
                TempData["error"] = "this is a test error";
                return RedirectToAction("Error", "Home");
            }
            return View(model);
        }


        public IActionResult DownloadFile(String id)
        {
            id = id.Replace("|", "/").Replace("_", "+").Replace("$", "=");
            string output = Encryption.SymmetricDecrypt(id);

            Guid fileId = new Guid(output);

            var _files = _studentWorkService.GetStudentWork();

            var file = _files.Where(x => x.Id == fileId).FirstOrDefault();
            var filename = file.filePath.Substring(7, 15);

            var url = new Uri(_env.ContentRootPath + file.filePath);

            var passw = Convert.ToBase64String(pwd);
            EncyrptFiles.FileDecrypt(url.LocalPath, filename, pwd, file.signature);

            MemoryStream FileM = new MemoryStream();

            WebClient webClient = new WebClient();

            webClient.DownloadFileCompleted += (sender, e) =>

SecuringApps.Application/SecuringApps.Presentation/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-Frame-Options" content="sameorigin"/>
    <title>@ViewData["Title"] - SecuringApps</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/js/jquery-3.5.1.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Securing Apps</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ContactUs">Contact Us</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            if (User.IsInRole("Student"))
                            {
                                <li class="nav-item">
                                      <a class="nav-link text-dark" asp-area="" asp-controller="StudentWork" asp-action="Index">Work</a>
                                </li>
                                <li class="nav-item">
                                     <a class="nav-link text-dark" asp-area="" asp-controller="StudentTask" asp-action="Index">All Tasks</a>
                                </li> 
                            }
                            if (User.IsInRole("Teacher"))
                            {
                                 <li class="nav-item">
                                     <a class="nav-link text-dark" asp-area="" asp-controller="StudentRegister" asp-action="Create">Student Creation</a>
                                 </li>
                                 <li class="nav-item">
                                     <a class="nav-link text-dark" asp-area="" asp-controller="StudentTask" asp-action="Create">Create Task</a>
                                 </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SecuringApps
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>