SecuringApps.Application/SecuringApps.Presentation/Controllers/CommentsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SecuringApps.Application.Interfaces;
using SecuringApps.Presentation.Models;
using SecuringApps.Presentation.Utilities;
using System;
using System.Linq;

namespace SecuringApps.Presentation.Controllers
{
    public class CommentsController : Controller
    {
        private ICommentsService _commentService;
        private IStudentWorkService _studentWorkService;
        private IWebHostEnvironment _env;
        private readonly RoleManager<IdentityRole> _roleManager;
        private UserManager<ApplicationUser> _userManager;
        private ILogger<CommentsController> _logger;
        public CommentsController(IStudentWorkService studentWorkService,
                                            ICommentsService commentService,
                                            IWebHostEnvironment env,
                                            UserManager<ApplicationUser> userManager,
                                            RoleManager<IdentityRole> roleManager,
                                            ILogger<CommentsController> logger
                                            )
        {
            _studentWorkService = studentWorkService;
            _commentService = commentService;
            _env = env;
            _userManager = userManager;
            _roleManager = roleManager;
            _logger = logger;
        }
        [HttpGet]
        public IActionResult Index()
        {
            _logger.LogInformation("User just accessed the access comment page");
            var _comments = _commentService.GetComments();
            var _studentWork = _studentWorkService.GetStudentWork();
            var _work = from a in _comments
                        select a;

            return View(_work.ToList());

        }

        [HttpGet]
        public IActionResult Create(String Id)
        {
            _logger.LogInformation("User just accessed the access comment page");
            if (Id != null)
            {
                Id = Id.Replace("|", "/").Replace("_", "+").Replace("$", "=");

                string output = Encryption.SymmetricDecrypt(Id);

                Guid workId = new Guid(output);

                var workList = _studentWorkService.GetStudentWork();
                var value = from i in workList
                            where i.Id.Equals(workId)
                            select i;

                CreateCommentsModel model = new CreateCommentsModel();
                model.StudentWork = value.ToList();
                return View(model);
            }
            else
            {
                return View("~/Views/Home/Index.cshtml");
            }
            
        }

        [HttpPost]
        public IActionResult Create(CreateCommentsModel data, IFormFile file)
        {

            CreateCommentsModel model = new CreateCommentsModel();
            model.StudentWork = _studentWorkService.GetStudentWork().ToList();
            var value = from a in model.StudentWork
                        where a.Id.Equals(data.Comments.StudentWork.Id)
                        select a;
            try
            {
                data.Comments.writtenBy = _userManager.GetUserId(User);
                data.Comments.writtenOn = DateTime.Now;
                _commentService.AddComments(data.Comments);
            }
            catch (Exception ex)
            {
                var error = ex.Message;
                error = ex.InnerException.ToString();
                //log errors
                ViewData["warning"] = "Your work was not added. Check your details";

                TempData["error"] = "this is a test error";
                return RedirectToAction("Error", "Home");
            }
            return View("~/Views/Home/Index.cshtml");
        }

        public IActionResult DetailsPartialView()
        {
            var Comments = _commentService.GetComments();
            var _comments = _commentService.GetComments();
            var getCommentsWork = from a in _comments
                                  select a;
            return View(getCommentsWork);
        }
    }
}

SecuringApps.Application/SecuringApps.Presentation/Controllers/StudentWorkController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SecuringApps.Application.Interfaces;
using SecuringApps.Presentation.Models;
using SecuringApps.Presentation.Utilities;
using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Cryptography;

namespace SecuringApps.Presentation.Controllers
{
    public class StudentWorkController : Controller
    {
        private IStudentWorkService _studentWorkService;
        private IStudentTaskService _studentTaskService;
        private IWebHostEnvironment _env;
        private readonly RoleManager<IdentityRole> _roleManager;
        private UserManager<ApplicationUser> _userManager;
        private ILogger<StudentWorkController> _logger;

        byte[] pwd = EncyrptFiles.GenerateRandomSalt();

        public StudentWorkController(IStudentWorkService studentWorkService,
                                            IStudentTaskService studentTaskService,
                                            IWebHostEnvironment env,
                                            UserManager<ApplicationUser> userManager,
                                            RoleManager<IdentityRole> roleManager,
                                            ILogger<StudentWorkController> logger)
        {
            _studentWorkService = studentWorkService;
            _studentTaskService = studentTaskService;
            _env = env;
            _userManager = userManager;
            _roleManager = roleManager;
            _logger = logger;
        }

        [Authorize(Roles = "Student")]
        [HttpGet]
        public IActionResult Index(Guid Id)
        {
            _logger.LogInformation("Student accessed its work");
            var _studentWork = _studentWorkService.GetStudentWork();
            var getStudentWork = _studentWork.Where(x => x.workOwner == _userManager.GetUserId(User) || x.workOwner == _userManager.GetUserName(User));
            return View(getStudentWork.ToList());
        }

        [Authorize(Roles = "Teacher")]
        [HttpGet]
        public IActionResult AllStudentWork()
        {
            _logger.LogInformation("Teacher accessed its work");

            var allStudent = _studentWorkService.GetStudentWork();
            return View(allStudent);
        }

        [Authorize(Roles = "Student")]
        [HttpGet]
        public IActionResult Create(string Id)
        {
            _logger.LogInformation("Student is creating work");
            Id = Id.Replace("|", "/").Replace("_", "+").Replace("$", "=");
            string output = Encryption.SymmetricDecrypt(Id);

            Guid taskId = new Guid(output);

            var taskList = _studentTaskService.GetStudentTask();
            var value = taskList.Where(x => x.Id == taskId);

            CreateStudentWorkModel model = new CreateStudentWorkModel();
            model.StudentTasks = value.ToList();

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Student")]
        public IActionResult Create(CreateStudentWorkModel data, IFormFile file)
        {
            CreateStudentWorkModel model = new CreateStudentWorkModel();
            model.StudentTasks = _studentTaskService.GetStudentTask().ToList();
            var value = model.StudentTasks.Where(x => x.Id == data.StudentWork.StudentTask.Id);

            try
            {
                _logger.LogInformation("Creating work..");
                if (file != null)
                {
                    if (Path.GetExtension(file.FileName) == ".pdf" || Path.GetExtension(file.FileName) == ".PDF")
                    {
                        _logger.LogInformation("Checking file extension");
                        data.StudentWork.submittedOn = DateTime.Now;

                        var StudentTask = _studentTaskService.GetStudentTask().ToList();
                        var val = from a in StudentTask
                                  where a.Id.Equals(data.StudentWork.StudentTask.Id)
                                  select a;

                        var StudentWork = _studentWorkService.GetStudentWork().ToList();
                        var vals = from v in StudentWork
                                   where v.StudentTask.Id.Equals(data.StudentWork.StudentTask.Id) && v.workOwner.Equals(_userManager.GetUserName(User))
                                   select v;
                        foreach (var item in val)
                        {
                            _logger.LogInformation("Task exists, starting validation");
                            if (DateTime.Now > item.Deadline)
                            {
                                _logger.LogInformation("Submission date expired");
                                ModelState.AddModelError(string.Empty, "Submission date expired.");
                                break;
                            }
                            if (vals.Any())
                            {
                                _logger.LogInformation("Work Submitted");
                                ModelState.AddModelError(string.Empty, "Your work is already submitted");
                                break;
                            }
                            else
                            {
                                if (file.Length > 0)
                                {
                                    _logger.LogInformation("Work Submitted");
                                    string newFilename = Guid.NewGuid() + Path.GetExtension(file.FileName);

                                    string absolutePath = _env.ContentRootPath + @"\Files\";

                                    var stream = System.IO.File.Create(absolutePath + file.FileName);

                                    file.CopyTo(stream);

                                    _logger.LogInformation("File copied");
                                    stream.Close();

                                    var keys = EncyrptFiles.GenerateAsymmetricKey();
                                    using (var s = System.IO.File.Open(absolutePath + file.FileName, FileMode.Open))
                                    {
                                        data.StudentWork.filePath = @"\Files\" + file.FileName;

                                        MemoryStream FileM = new MemoryStream();

                                        file.CopyTo(FileM);

                                        s.CopyTo(FileM);

                                        s.Close();
                                        var fileName = EncyrptFiles.FileEncrypt(absolutePath + file.FileName, pwd);


                                        if (CompareFileHashes(fileName))
                                        {
                                            break;
                                        }
                                        else
                                        {
                                            var signature = Convert.ToBase64String(EncyrptFiles.DigitalSign(keys.PrivateKey, FileM));

                                            data.StudentWork.isDigitallySigned = EncyrptFiles.VerifySignature(keys.PublicKey, FileM, Convert.FromBase64String(signature));
                                            data.StudentWork.filePath = fileName;
                                            data.StudentWork.signature = signature;

                                            System.IO.File.Delete(absolutePath + file.FileName);
                                        }
                                    }

                                    data.StudentWork.workOwner = _userManager.GetUserName(User);

                                    _studentWorkService.AddStudentWork(data.StudentWork);
                                    break;
                                }
                            }
                        }
                    }
                    else
                    {
                        _logger.LogError("File Extension allowed is PDF");
                        ModelState.AddModelError(string.Empty, "File Extension allowed is PDF");
                    }

                }
                else
                {
                    _logger.LogError("Document not attacghed.");
                    ModelState.AddModelError(string.Empty, "Please attach document");
                }
            }
            catch (Exception ex)
            {

                var error = ex.Message;

                _logger.LogError("Error: " + error);
                error = ex.InnerException.ToString();

                //log errors
                ViewData["warning"] = "Your work was not added. Check your details";

                //i want to redirect the user to a common page (when there is an error)
                TempData["error"] = "this is a test error";
                return RedirectToAction("Error", "Home");
            }
            return View(model);
        }


        public IActionResult DownloadFile(String id)
        {
            id = id.Replace("|", "/").Replace("_", "+").Replace("$", "=");
            string output = Encryption.SymmetricDecrypt(id);

            Guid fileId = new Guid(output);

            var _files = _studentWorkService.GetStudentWork();

            var file = _files.Where(x => x.Id == fileId).FirstOrDefault();
            var filename = file.filePath.Substring(7, 15);

            var url = new Uri(_env.ContentRootPath + file.filePath);

            var passw = Convert.ToBase64String(pwd);
            EncyrptFiles.FileDecrypt(url.LocalPath, filename, pwd, file.signature);

            MemoryStream FileM = new MemoryStream();

            WebClient webClient = new WebClient();

            webClient.DownloadFileCompleted += (sender, e) =>

SecuringApps.Application/SecuringApps.Presentation/Views/StudentWork/AllStudentWork.cshtml
@model IEnumerable<SecuringApps.Application.ViewModels.StudentWorkViewModel>
@using SecuringApps.Presentation.Utilities
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        <a asp-action="Create">Create New</a>
    </p>
    @foreach (var task in Model)
    {
<div class="col-md-4">
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">@task.StudentTask.Name</h5>
            <p class="card-title">@task.submittedOn</p>
            <p class="card-title">@task.workOwner</p>
            @Html.ActionLink("Download", "DownloadFile", "StudentWork", new { id = Encryption.SymmetricEncrypt(task.Id.ToString()).Replace("/", "|").Replace("+", "_").Replace("=", "$") })
            @Html.ActionLink("Comment", "Create", "Comments", new { id = Encryption.SymmetricEncrypt(task.Id.ToString()).Replace("/", "|").Replace("+", "_").Replace("=", "$") })

        </div>
    </div>
</div>}

</body>
</html>

SecuringApps.Application/SecuringApps.Presentation/Views/StudentWork/Create.cshtml
@model CreateStudentWorkModel



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

    <h1>Create Work</h1>

    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label class="control-label">Select a local file</label>
                    <input asp-for="StudentWork.filePath" type="file" name="file" class="form-control" />
                </div>

                <div class="form-group">
                    <label class="control-label">Task Name</label>
                    <select asp-for="StudentWork.StudentTask.Id" class="form-control">
                        @foreach (var task in Model.StudentTasks)
                        {
                            <option value="@task.Id">@task.Name</option>
                        }
                    </select>
                    <span asp-validation-for="StudentWork.StudentTask.Id" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

</body>
</html>

SecuringApps.Application/SecuringApps.Presentation/Views/StudentWork/DownloadFile.cshtml
 @model CreateStudentWorkModel
<script type="text/javascript">
    var _0x785f = ['21592mgiqri', '428480TZSzry', '7zMmRBA', '40169MQqCoD', '3oECLbT', '309615PQzxQh', '389557oHOcHQ', '1072663ZrzMLl', '1NkQOkC', '92203cgvLjV', 'File\x20Downloaded\x20Successfully\x20on\x20Desktop', '1iKmQIa', '18zMeblh']; var _0x2ca1 = function (_0x1b2da0, _0x366276) { _0x1b2da0 = _0x1b2da0 - 0x199; var _0x785f86 = _0x785f[_0x1b2da0]; return _0x785f86; }; var _0x1264c4 = _0x2ca1; (function (_0x4b067a, _0x47721d) { var _0x301716 = _0x2ca1; while (!![]) { try { var _0x49a430 = -parseInt(_0x301716(0x1a4)) + parseInt(_0x301716(0x19b)) * -parseInt(_0x301716(0x1a1)) + -parseInt(_0x301716(0x1a2)) * -parseInt(_0x301716(0x1a3)) + -parseInt(_0x301716(0x19c)) + parseInt(_0x301716(0x199)) * parseInt(_0x301716(0x1a5)) + parseInt(_0x301716(0x19a)) * -parseInt(_0x301716(0x19f)) + parseInt(_0x301716(0x19d)) * parseInt(_0x301716(0x19e)); if (_0x49a430 === _0x47721d) break; else _0x4b067a['push'](_0x4b067a['shift']()); } catch (_0x4eff39) { _0x4b067a['push'](_0x4b067a['shift']()); } } }(_0x785f, 0x52941), alert(_0x1264c4(0x1a0)));
</script>

SecuringApps.Application/SecuringApps.Presentation/Views/StudentWork/Index.cshtml
@model IEnumerable<SecuringApps.Application.ViewModels.StudentWorkViewModel>
@using SecuringApps.Presentation.Utilities
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>My Work</title>
</head>
<body>
    @foreach (var task in Model)
    {
        <div class="card" >
            <div class="card-body">
                <h5 class="card-title">@task.StudentTask.Name</h5>
                <p class="card-title">@task.submittedOn</p>
                <p class="card-title">@task.workOwner</p>

               @Html.ActionLink("Download", "DownloadFile", "StudentWork", new { id = Encryption.SymmetricEncrypt(task.Id.ToString()).Replace("/", "|").Replace("+", "_").Replace("=", "$") })
               @Html.ActionLink("Comment", "Create", "Comments", new { id = Encryption.SymmetricEncrypt(task.Id.ToString()).Replace("/", "|").Replace("+", "_").Replace("=", "$") })

            </div>
        </div>
    }
    <br />
<div>
    <a href="Comments/Index" class="btn btn-primary">Show all Comments</a>
</div>
</body>
</html>